CREATE TABLE cursor_storage (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source       varchar(255) NOT NULL,
    cursor_value varchar(255) NOT NULL,
    CONSTRAINT uq_cursor_storage_source UNIQUE (source)
);

CREATE TABLE npm_package (
    package_id                  varchar(255) PRIMARY KEY,
    deleted                     boolean      NOT NULL DEFAULT false,
    name                        varchar(255),
    latest_version              varchar(255),
    description                 text,
    keywords                    text[],
    license                     varchar(255),
    date_package_created        timestamptz  NOT NULL,
    date_package_modified       timestamptz  NOT NULL,
    date_latest_version_modified timestamptz
);
